development:
  adapter: postgresql
  database: paleio
  username: paleio
  password: dev
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: postgresql
  database: paleio
  username: paleio
  password: dev
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: paleio
  username: paleio
  password: dev
  pool: 5
  timeout: 5000
  encoding: utf8
